{
    "name": "​ConnectedAppPlugin​Exception",
    "namespace": "Auth",
    "accessModifier": "global",
    "definitionModifier": "",
    "withSharing": false,
    "inheritedSharing": false,
    "isEnum": false,
    "enumValues": [],
    "extendsType": "Exception",
    "isInterface": false,
    "implements": [],
    "classes": {},
    "enums": {},
    "fields": [],
    "constructors": [],
    "methods": [],
    "description": "Throw this exception to indicate that an error occurred while running the custom behavior for a connected app.",
    "docLink": "https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_Auth_exceptions.htm"
}